Configuration Hylanotify
---
tags:
  - HylaNotify
description: Renvoie la derniere version de la config pour HylaNotify en vérifiant a partir du checksum renvoyé si elle le config.remote.json
parameters:
  - name: checksum
    in: query
    type: string
    required: false
    description: Le checksum de la config HylaNotify se trouvant dans le fichier config.remote.json 
responses:
  '200':
    description: "config retourné sous forme de json"
    schema:
      $ref: '#/definitions/json'
    examples:
      title: "Get conf"
      description: ""
      status: "OK"
      items: ""